# Use root/example as user/password credentials
version: '3.9'

services:
  dev:
    build:
      context: ./src
    ports:
      - 3000:3000
    networks:
      - default
    command: npm start
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    command: [mongod, --dbpath, /data/db]
    ports:
      - 27017
    volumes:
      - $PWD/data:/data/db
    networks:
      - default
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: r00t

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - default
    ports:
      - 8081:8081
    environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: r00t
      # ME_CONFIG_MONGODB_URL: mongodb://root:r00t@mongo:27017/
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

  redis:
    image: redis:latest
    restart: always
    networks:
      - default
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --requirepass MDNcVb924a --loglevel warning
    volumes:
      - $DOCKERDIR/appdata/redis/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

networks:
  default:
    driver: bridge
